language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
    - php: 7.2
    - php: 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

script:
  - composer install
  - vendor/bin/phpunit
